version: '3'

services:
    php:
      build: ./docker/php/
      ports:
        - 80:80
      volumes:
          - ./:/var/www/
    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: 1234
        POSTGRES_USER: leha
        POSTGRES_DB: rzcol
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
  # phpmyadmin:
    zookeeper:
      image: wurstmeister/zookeeper
      ports:
      - 2181:2181
#    volumes:
#      - zkdata:/data
    kafka:
      image: wurstmeister/kafka
      ports:
      - 9092:9092
      environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_CREATE_TOPICS: "test:1:1"
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
        - zookeeper
    kafka-ui:
      image: provectuslabs/kafka-ui
      container_name: kafka-ui
      ports:
        - "3333:8080"
      restart: always
      environment:
        - KAFKA_CLUSTERS_0_NAME=local
        - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
        - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
        - KAFKA_CLUSTERS_0_READONLY=false
